const subjects = [
  'Mathematics',
  'Physics',
  'Chemistry',
  'Biology',
  'Medicine',
  'Engineering',
  'Psychology',
  'Sociology',
  'Economics',
  'History',
  'Geography',
  'Politics',
  'Philosophy',
  'Literature',
  'Art',
  'Music',
  'Computer Science',
  'Environmental Science',
  'Astronomy',
  'Geology',
  'Anthropology',
  'Linguistics',
  'Law',
  'Education',
  'Business',
  'Finance',
  'Accounting',
  'Marketing',
  'Drawing',
  'Guitar',
  'Ethics',
  'Theology',
  'Cultural Studies',
  'Gender Studies',
  'Information Technology',
  'Agriculture',
  'Architecture',
  'Sports Science',
  'Nutrition',
  'Public Health',
  'Veterinary Science',
  'Oceanography',
  'Meteorology',
  'Pharmacy',
  'Neuroscience',
  'Urban Planning',
  'Tourism',
  'International Relations',
  'Human Rights',
  'Public Policy',
  'Forestry',
  'Archaeology',
  'Communication',
  'Journalism',
  'Film Studies',
  'Theater',
  'Dance',
  'Graphic Design',
  'Fashion',
  'Industrial Design',
  'Artificial Intelligence',
  'Data Science',
  'Cybersecurity',
  'Machine Learning',
  'Nanotechnology',
  'Renewable Energy',
  'Quantum Computing',
  'Biotechnology',
  'Genetics',
  'Immunology',
  'Epidemiology',
  'Climatology',
  'Astrophysics',
  'Molecular Biology',
  'Organic Chemistry',
  'Statistics',
  'Calculus',
  'Algebra',
  'Geometry',
  'Number Theory',
  'Logic',
  'Differential Equations',
  'Topology',
  'Materials Science',
  'Electrical Engineering',
  'Mechanical Engineering',
  'Civil Engineering',
  'Chemical Engineering',
  'Aerospace Engineering',
  'Nuclear Engineering',
  'Software Engineering',
  'Automotive',
  'Robotics',
  'Microbiology',
  'Forensic Science',
  'Cognitive Science',
  'Game Theory',
  'Operations Research',
  'Demography',
  'Developmental Psychology',
  'Clinical Psychology',
  'Counseling',
  'Social Work',
  'Human Geography',
  'Physical Geography',
  'Paleontology',
  'Entomology',
  'Ichthyology',
  'Herpetology',
  'Ornithology',
  'Mammalogy',
  'Marine Biology',
  'Conservation Biology',
  'Ecology',
  'Evolution',
  'Behavioral Science',
  'Management',
  'Human Resources',
  'Supply Chain',
  'Entrepreneurship',
  'Real Estate',
  'Corporate Governance',
  'Investment',
  'Risk Management',
  'Taxation',
  'Banking',
  'Insurance',
  'International Trade',
  'Econometrics',
  'Macroeconomics',
  'Microeconomics',
  'Political Science',
  'Civic Education',
  'Public Administration',
  'European Studies',
  'Asian Studies',
  'African Studies',
  'Latin American Studies',
  'Middle Eastern Studies',
  'Russian Studies',
  'American Studies',
  'Indigenous Studies',
  'Classical Studies',
  'Renaissance Studies',
  'Modern History',
  'World History',
  'Medieval History',
  'Ancient History',
  'American History',
  'European History',
  'Asian History',
  'African History',
  'Middle Eastern History',
  'Latin American History',
  'Canadian History',
  'Russian History',
  "Women's History",
  'Military History',
  'Art History',
  'Music Theory',
  'Composition',
  'Performance',
  'Musicology',
  'Ethnomusicology',
  'Acoustics',
  'Sound Engineering',
  'Film Production',
  'Animation',
  'Photography',
  'Printmaking',
  'Sculpture',
  'Ceramics',
  'Textile Design',
  'Jewelry Design',
  'Product Design',
  'Interior Design',
  'Landscape Architecture',
  'Urban Design',
  'Planning Law',
  'Property Law',
  'Criminal Law',
  'Constitutional Law',
  'International Law',
  'Humanitarian Law',
  'Tax Law',
  'Corporate Law',
  'Family Law',
  'Environmental Law',
  'Intellectual Property Law',
  'Labor Law',
  'Maritime Law',
  'Medical Law',
  'Human Resource Development',
  'Adult Education',
  'Special Education',
  'Educational Technology',
  'Curriculum Development',
  'Pedagogy',
  'Language Teaching',
  'Physical Education',
  'Health Education',
  'Museum Studies',
  'Library Science',
  'Archival Studies',
  'Book Studies',
  'Comparative Literature',
  'Creative Writing',
  'Rhetoric',
  'Poetry',
  'Prose',
  'Drama',
  'Non-Fiction',
  'Folklore',
  'Mythology',
  'Science Fiction',
  'Fantasy',
  'Mystery',
  'Horror',
  'Romance',
  'Satire',
  'Tragedy',
  'Comedy',
  'Criticism',
  'Narrative Studies',
  'Philosophy of Science',
  'Philosophy of Mind',
  'Metaphysics',
  'Epistemology',
  'Political Philosophy',
  'Religious Studies',
  'Biblical Studies',
  'Islamic Studies',
  'Hindu Studies',
  'Buddhist Studies',
  'Judaic Studies',
  'Sikh Studies',
  'Daoist Studies',
  'Comparative Religion',
  'Mythology',
  'Spirituality',
  'Divinity',
  'Pastoral Care',
  'Homiletics',
  'Liturgics',
  'Canon Law',
  'Church History',
  'Systematic Theology',
  'Moral Theology',
  'Practical Theology',
  'Religious Education',
  'Missionary Studies',
  'Ecumenism',
  'Patristics',
  'Eschatology',
  'Kinesiology',
  'Exercise Science',
  'Sports Management',
  'Sports Psychology',
  'Coaching',
  'Recreation Management',
  'Outdoor Education',
  'Dietetics',
  'Food Science',
  'Food Technology',
  'Public Nutrition',
  'Clinical Nutrition',
  'Community Health',
  'Health Policy',
  'Occupational Health',
  'Epidemiology',
  'Biostatistics',
  'Health Informatics',
  'Health Economics',
  'Global Health',
  'Maternal Health',
  'Child Health',
  'Veterinary Medicine',
  'Animal Nutrition',
  'Animal Behavior',
  'Zoology',
  'Veterinary Surgery',
  'Veterinary Pathology',
  'Animal Welfare',
  'Veterinary Pharmacology',
  'Oceanography',
  'Marine Science',
  'Fisheries Science',
  'Aquaculture',
  'Marine Conservation',
  'Marine Engineering',
  'Naval Architecture',
  'Hydrology',
  'Atmospheric Science',
  'Climate Science',
  'Physical Oceanography',
  'Chemical Oceanography',
  'Biological Oceanography',
  'Meteorology',
  'Weather Forecasting',
  'Climate Modelling',
  'Atmospheric Chemistry',
  'Atmospheric Physics',
  'Pharmaceutics',
  'Pharmacology',
  'Toxicology',
  'Pharmacy Practice',
  'Medicinal Chemistry',
  'Pharmacognosy',
  'Pharmacoeconomics',
  'Pharmacy Law',
  'Pharmacy Administration',
  'Neurology',
  'Psychiatry',
  'Cardiology',
  'Oncology',
  'Dermatology',
  'Gastroenterology',
  'Endocrinology',
  'Pulmonology',
  'Nephrology',
  'Rheumatology',
  'Orthopedics',
  'Ophthalmology',
  'Otorhinolaryngology',
  'Gynecology',
  'Obstetrics',
  'Pediatrics',
  'Surgery',
  'Anesthesiology',
  'Radiology',
  'Pathology',
  'Emergency Medicine',
  'Family Medicine',
  'Internal Medicine',
  'Occupational Medicine',
  'Sports Medicine',
  'Rehabilitation Medicine',
  'Pain Management',
  'Palliative Care',
  'Geriatrics',
  'Infectious Diseases',
  'Tropical Medicine',
  'Travel Medicine',
  'Immunotherapy',
  'Vaccinology',
  'Translational Medicine',
  'Personalized Medicine',
  'Regenerative Medicine',
  'Stem Cell Research',
  'Python',
  'JavaScript',
  'Java',
  'C++',
  'C#',
  'Ruby',
  'PHP',
  'Swift',
  'Kotlin',
  'Go',
  'Rust',
  'TypeScript',
  'SQL',
  'HTML',
  'CSS',
  'Sass',
  'React',
  'Angular',
  'Vue.js',
  'Node.js',
  'Django',
  'Flask',
  'Spring',
  'Ruby on Rails',
  'ASP.NET',
  'Laravel',
  'TensorFlow',
  'PyTorch',
  'Keras',
  'Machine Learning',
  'Deep Learning',
  'Data Analysis',
  'Data Visualization',
  'Big Data',
  'Hadoop',
  'Spark',
  'NoSQL',
  'MongoDB',
  'Cassandra',
  'Oracle DB',
  'MySQL',
  'PostgreSQL',
  'Microsoft SQL Server',
  'Blockchain',
  'Ethereum',
  'Smart Contracts',
  'Cybersecurity',
  'Penetration Testing',
  'Ethical Hacking',
  'Cloud Computing',
  'AWS',
  'Azure',
  'Google Cloud',
  'Docker',
  'Kubernetes',
  'DevOps',
  'CI/CD',
  'Git',
  'Agile Methodologies',
  'Scrum',
  'Kanban',
  'UX/UI Design',
  'Figma',
  'Sketch',
  'Adobe XD',
  'InVision',
  'Wireframing',
  'Prototyping',
  'Information Architecture',
  'User Research',
  'SEO',
  'SEM',
  'Content Management',
  'Wordpress',
  'Drupal',
  'Joomla',
  'Shopify',
  'Magento',
  'E-commerce',
  'Digital Marketing',
  'Social Media Marketing',
  'Email Marketing',
  'Affiliate Marketing',
  'PPC',
  'CRM',
  'Salesforce',
  'Zoho',
  'Mobile Development',
  'iOS Development',
  'Android Development',
  'React Native',
  'Xamarin',
  'Ionic',
  'Unity',
  'Game Development',
  'AR/VR',
  '3D Modeling',
  'Blender',
  'Maya',
  '3ds Max',
  'AutoCAD',
  'Revit',
  'GIS',
  'QGIS',
  'ESRI',
  'AI Ethics',
  'Quantum Computing',
  'IoT',
  'Embedded Systems',
  'Microcontrollers',
  'Raspberry Pi',
  'Arduino',
  'Linux',
  'Bash Scripting',
  'PowerShell',
  'Systems Administration',
  'Network Engineering',
  'Cisco Technologies',
  'VMware',
  'Windows Server',
  'Help Desk Support',
  'Technical Writing',
  'Project Management',
  'PMP',
  'Lean Six Sigma',
  'Data Privacy',
  'GDPR',
  'ISO Standards',
  'Accessibility',
  'Quality Assurance',
  'Software Testing',
  'Automated Testing',
  'Selenium',
  'API Development',
  'RESTful Services',
  'GraphQL',
  'WebSockets',
  'MERN Stack',
  'MEAN Stack',
  'LAMP Stack',
  'Software Architecture',
  'Microservices',
  'Serverless Architecture',
  'Business Intelligence',
  'Tableau',
  'Power BI',
  'SAP',
  'Excel',
  'VBA',
  'Data Science',
  'Natural Language Processing',
  'Computer Vision',
  'Speech Recognition',
  'Reinforcement Learning',
  'Edge Computing',
  'Digital Twin',
  'IT Strategy',
  'Agile Coaching',
  'Scalability',
  'High Availability',
  'Performance Tuning',
  'Release Management',
  'ITIL',
  'COBIT',
  'Risk Management',
  'Information Security',
  'Cryptography',
  'Blockchain Development',
  'NFTs',
  'Metaverse',
  'Web3',
  'Solidity',
  'Truffle',
  'Hardhat',
  'Web Assembly',
  'RPA',
  'UiPath',
  'Automation Anywhere',
  'Blue Prism',
  'Version Control',
  'Subversion',
  'Mercurial',
  'Bitbucket',
  'GitLab',
  'CI Tools',
  'Jenkins',
  'CircleCI',
  'Travis CI',
  'Code Quality',
  'SonarQube',
  'Linting',
  'Static Code Analysis',
  'Code Review',
  'Pair Programming',
  'Extreme Programming',
  'Functional Programming',
  'Object-Oriented Programming',
  'Event-Driven Architecture',
  'Domain-Driven Design',
  'API Design',
  'Design Patterns',
  'Clean Code',
  'Refactoring',
  'Debugging',
  'Performance Profiling',
  'Load Testing',
  'Stress Testing',
  'User Acceptance Testing',
  'Software Deployment',
  'Feature Flags',
  'A/B Testing',
  'Multivariate Testing',
  'Conversion Rate Optimization',
  'Growth Hacking',
  'IT Operations',
  'IT Service Management',
  'Network Security',
  'Firewall Management',
  'Intrusion Detection',
  'Disaster Recovery',
  'Business Continuity',
  'Incident Management',
  'Problem Management',
  'Service Desk',
  'Change Management',
  'Capacity Planning',
  'IT Asset Management',
  'License Management',
  'IT Compliance',
  'Vulnerability Management',
  'Patch Management',
  'Data Center Management',
  'IT Procurement',
  'Vendor Management',
  'Contract Management',
  'IT Governance',
  'Enterprise Architecture',
  'TOGAF',
  'Zachman Framework',
  'IT Budgeting',
  'Cost Control',
  'Resource Allocation',
  'IT Auditing',
  'Sarbanes-Oxley',
  'HIPAA',
  'PCI DSS',
  'ISO 27001',
  'FISMA',
  'NIST Framework',
  'Cybersecurity Framework',
  'Threat Intelligence',
  'Security Operations Center',
  'Digital Forensics',
  'Incident Response',
  'Security Awareness Training',
  'Phishing Simulation',
  'Encryption',
  'Public Key Infrastructure',
  'Certificate Management',
  'Identity and Access Management',
  'Single Sign-On',
  'Multi-Factor Authentication',
  'Privileged Access Management',
  'Security Information and Event Management',
  'Log Management',
  'Network Monitoring',
  'Application Monitoring',
  'System Monitoring',
  'Database Monitoring',
  'Cloud Monitoring',
  'End-User Experience Monitoring',
  'Synthetic Monitoring',
  'Real User Monitoring',
  'Application Performance Management',
  'Network Performance Management',
  'Storage Performance Management',
  'IT Performance Management',
  'Capacity Management',
  'Resource Optimization',
  'Cloud Optimization',
  'Cost Management',
  'Cloud Migration',
];

export default subjects;
